language: go

services:
  - docker

install: "docker build -t opencv:latest -t opencv:latest ."

after_success:
  - docker login -u"$DOCKERHUB_USERNAME" -p"$DOCKERHUB_PASSWORD"
  - docker push iamkai/opencv-docker-golang:latest
